### ISSUE TITLE
[Feature request] Message Notification

### ISSUE THREAD

**Issue by naiba** [LemmurOrg/lemmur#228]
Hi, is it possible to receive system notifications of new messages while the app is running in the background?

**Comment by krawieck** [comment]
We plan on adding notifications when in app, but I don't think we can do that with the app in the background without taking a big toll on the battery. That's because in the back end it's currently made in such a way that we have to constantly listen to web socket

**Comment by dessalines** [comment]
I know that most reddit apps for android use timed background polling (Every hour, 30 minutes, 15 minutes, etc ) . That would be possible to do separate from websocket, which could do live in-app notifs, but I agree you wouldn't want to run it in the background.

**Comment by trymeouteh** [comment]
Would like to see this for degoofled devices. Maybe to have it check every X minutes to reduce battery usage

**Comment by schnuppikarotti** [comment]
could [unified push](https://unifiedpush.org/) be an option?

**Comment by Tealk** [comment]
Is the topic of notification still relevant? Because it is closed but it was neither agreed nor disagreed.
