### ISSUE TITLE
Clipboard access toast message in Android 12

### ISSUE THREAD

**Issue by duckduck1** [LemmurOrg/lemmur#287]
When launching Lemmur Android 12 shows a toast notification that 'Lemmur pasted from your clipboard'.

From a user perspective it is not plausible that the clipboard is accessed without the intent to paste anything.

Steps to reproduce:
1. Force close Lemmur
2. Copy text from within another app
3. Open Lemmur
4. Android privacy toast notification appears

Can you please clarify why the clipboard is accessed upon app start and/or consider changing the behavior as it can be confusing for users with privacy in mind.

**Comment by shilangyu** [comment]
This is indeed weird, I can't think of a single reason why lemmur would be reading the clipboard. We will look into it.

**Comment by shilangyu** [comment]
https://github.com/flutter/flutter/issues/74139#issuecomment-933391791

Looks like it is a flutter bug, fixed upstream but not released in the stable channel.

**Comment by shilangyu** [comment]
This should disappear on our next release, we have upgraded Flutter to a new version with this fix

**Comment by IL2P** [comment]
I came here to report this issue. My paranoia was peaking. I'm glad it was just a bug
