### ISSUE TITLE
Unable to build Lemmur using flutter

### ISSUE THREAD

**Issue by DokStook** [LemmurOrg/lemmur#311]
### Describe the bug

Unable to build .apk with flutter

### Steps to reproduce

1. Git clone the repo
2. cd into the folder
3. execute the provided buil command

### Relevant logs

Target file "lib/main.dart" not found.>

### Expected behavior

Getting built version of the app

![ksnip_20220106-173127](https://user-images.githubusercontent.com/31543930/148407564-d0f55bb8-24e1-4d18-91d3-aafaca6ad9c6.png)

**Comment by shilangyu** [comment]
Looks like our readme is outdated. We have recently switched to flavors, so to build lemmur run:

```
flutter build apk -t lib/main_prod.dart --release --flavor prod
```

Will update readme in a moment

**Comment by DokStook** [comment]
Now I have the problem 

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageProdRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > SigningConfig "prod" is missing required property "storeFile".
`

**Comment by shilangyu** [comment]
Ah. Right. It needs to be signed. I'll see what I can do about it

**Comment by DokStook** [comment]
Thanks! Waiting for an update

**Comment by shilangyu** [comment]
Added fallback to debug signing keys. Try building from the `fix/debug-fallback` branch
